name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        default: 'ps4-linux-6.15.y'
        type: choice
        options:
          - ps4-linux-6.15.y-baikal
          - ps4-linux-6.15.y
          - ps4-linux-6.12.y
          - ps4-linux-6.9.y
          - ps4-linux-6.8.y
          - ps4-linux-6.6.y
          - ps4-linux-6.1.y
          - ps4-linux-5.16.y
          - ps4-linux-5.15.y
          - linux-5.15.y
          - master
      create_release:
        description: 'Create a release?'
        required: true
        default: false
        type: boolean
      release_name:
        description: 'Release name (optional, defaults to branch name)'
        required: false
        type: string

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential flex bison libssl-dev libelf-dev bc dwarves clang llvm

      - name: Copy custom config
        run: |
          cp config .config

      - name: Install WiFi firmware
        run: |
          mkdir -p lib/firmware/mrvl
          cd lib/firmware/mrvl
          wget https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/mrvl/sd8897_uapsta.bin
          wget https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/mrvl/sd8797_uapsta.bin
          cd ../../..
          sed -i 's,CONFIG_EXTRA_FIRMWARE_DIR="/lib/firmware",CONFIG_EXTRA_FIRMWARE_DIR="lib/firmware",g' .config

      - name: Build kernel
        run: |
          make -j$(nproc)

      - name: Build bzImage
        run: |
          make bzImage

      - name: Upload bzImage as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: bzImage
          path: arch/x86/boot/bzImage

      - name: Create Release
        if: ${{ inputs.create_release }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.branch }}
          name: ${{ inputs.release_name || inputs.branch }}
          files: arch/x86/boot/bzImage
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
